version: "3.9"

services:
 backend:
  build: .
  container_name: todo
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/core
  ports:
   - "8000:8000"
 db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    
